# Timothy Owen
# 11 June 2025
# Quick exercise to take a list of 'employees' from a CSV, split the full name
# into First, Last Name, and export to a new file.

# Open the file: imaginary_data.csv, generated by Grok

try:
    with open("imaginary_data.csv", 'r') as input_file:
        file_rows = [line.strip() for line in input_file]
except FileNotFoundError:
    print("Error: imaginary_data.csv not found.")

# Split line into fields
for index, row in enumerate(file_rows):
    file_rows[index] = row.split(",")

new_rows = []
header_row = file_rows[0]   # separate out header from data rows
data_rows = file_rows[1:]

# Process name into First and Last Names
name_index = header_row.index("Full Name")  # Avoids using magic numbers
header_row[name_index] = "First Name,Last Name"
header_row = ",".join(header_row)           # List becomes a string
new_rows.append(header_row)

for index, row in enumerate(data_rows):
    row[name_index] = row[name_index].replace(" ", ",", 1)
    data_rows[index] = ",".join(row)
    new_rows.append(data_rows[index])


# Combine entries into csv
new_file = "\n".join(new_rows)

# Write the file
input_file.close()
output_file = open("processed_imaginary_data.csv", 'w')
output_file.write(new_file)
output_file.close()

